ARG ARCH=
FROM ${ARCH}node:22-bookworm AS build
WORKDIR /app
ENV DOCKER=YES NODE_ENV=production
ADD ./MMirakurun .
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends build-essential && \
    npm ci --include=dev && \
    npm run build && \
    npm ci --omit=dev
COPY ./container-init.sh docker/

FROM ${ARCH}node:22-bookworm-slim
WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        make \
        gcc \
        g++ \
        pkg-config \
        pcscd \
        libpcsclite-dev \
        libccid \
        libdvbv5-dev \
        pcsc-tools \
        dvb-tools \
        autoconf \
        automake \
        cmake \
        pkg-config \
        libssl-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /app /app
CMD ["./docker/container-init.sh"]
EXPOSE 40772 9229
